on:
    push:
        branches:
            - main

jobs:
    build: 
        name: Build Web and Deploy
        runs-on: windows-latest
        env: 
            BASE_HREF: /${{ github.event.repository.name }}/
        steps:
            - name: Checkout code
              uses: actions/checkout@v2  # Updated to v2 (v1 is deprecated)

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.27.1'
                channel: 'stable'

            - name: Install dependencies
              run: flutter pub get

            - name: Build web app
              run: flutter build web --release

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3  # v3 is fine, no update needed
              if: github.ref == 'refs/heads/main'
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build/web
