on:
    push:
        branches:
            - main
jobs:
    build: 
        name: Build Web and Deploy
        runs-on: windows-latest
        env: 
            BASE_HREF: /${{github.event.repository.name}}/
        steps:
            - uses: actions/checkout@v1
            - uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.27.1'
                channel: 'stable'
            - run: flutter pub get
            - run: flutter build web --release --base-href $BASE_HREF
            - name: Deploy gh-pages
              uses: peaceiris/actions-gh-pages@v4
              if: github.ref == 'refs/heads/main'
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build/web